# Generated by Django 4.2.2 on 2023-07-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vendor_date_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('In_review', 'In review'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('published', 'Published')], default='In_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(4, '★★★★☆'), (2, '★★☆☆☆'), (5, '★★★★★'), (3, '★★★☆☆'), (1, '★☆☆☆☆')], default=None),
        ),
    ]
