# Generated by Django 4.2.2 on 2023-07-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mfd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(blank=True, default='10', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('delivered', 'Delivered'), ('process', 'Processing')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('In_review', 'In review'), ('published', 'Published'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='In_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(5, '★★★★★'), (1, '★☆☆☆☆'), (4, '★★★★☆'), (2, '★★☆☆☆'), (3, '★★★☆☆')], default=None),
        ),
    ]
