# Generated by Django 4.2.2 on 2023-07-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_mfd_product_stock_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('process', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('In_review', 'In review'), ('rejected', 'Rejected'), ('disabled', 'Disabled'), ('draft', 'Draft'), ('published', 'Published')], default='In_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(blank=True, default='10', null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(5, '★★★★★'), (2, '★★☆☆☆'), (1, '★☆☆☆☆'), (4, '★★★★☆'), (3, '★★★☆☆')], default=None),
        ),
    ]
