# Generated by Django 4.2.2 on 2023-07-28 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='wishlist_model',
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('delivered', 'Delivered'), ('processing', 'Processing')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('rejected', 'Rejected'), ('published', 'Published'), ('In_review', 'In review'), ('draft', 'Draft')], default='In_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(5, '★★★★★'), (4, '★★★★☆'), (3, '★★★☆☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆')], default=None),
        ),
    ]
