# Generated by Django 4.2.2 on 2023-07-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('In_review', 'In review')], default='In_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(3, '★★★☆☆'), (2, '★★☆☆☆'), (4, '★★★★☆'), (5, '★★★★★'), (1, '★☆☆☆☆')], default=None),
        ),
    ]
